# Generated by Django 3.1.5 on 2021-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='caption',
            field=models.CharField(max_length=20000),
        ),
    ]
