# Generated by Django 3.1.5 on 2021-03-11 16:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210311_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userimage',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1615479030/promedia/profiles/defauly_qtracn.png', max_length=255, verbose_name='image'),
        ),
    ]
