# Generated by Django 3.0.8 on 2020-08-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200820_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userimage',
            field=models.ImageField(default='/media/profile/samplepost.jpg', upload_to='profiles/'),
        ),
    ]
