# Generated by Django 3.1.5 on 2021-03-11 17:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210311_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userimage',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1615483067/promedia/profiles/defauly_kg8d7c.jpg', max_length=255, verbose_name='image'),
        ),
    ]
