# Generated by Django 3.0.8 on 2020-08-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200820_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userimage',
            field=models.ImageField(default='profile/samplepost.jpg', upload_to='profiles/'),
        ),
    ]
