# Generated by Django 3.0.8 on 2020-08-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200820_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userimage',
            field=models.ImageField(default='profiles/samplepost.png', upload_to='profiles/'),
        ),
    ]
